-- Phase 2: idempotent admin catalog seed for category hierarchy and Barry Callebaut products.
-- Existing legacy categories/products are preserved. Rows below are upserted by id.

insert into public.categories (
  id,
  name,
  slug,
  description,
  parent_id,
  sort_order,
  is_visible,
  is_active,
  seo_title,
  seo_description,
  image_url
)
values
  (
    'cat-cafe-insumos',
    'Cafe e insumos',
    'cafe-insumos',
    'Cafe, bebidas instantaneas e insumos profesionales para vending y cafeteria.',
    null,
    10,
    true,
    true,
    'Cafe e insumos | SMK Vending',
    'Cafe, bebidas instantaneas e insumos profesionales para vending y cafeteria.',
    null
  ),
  (
    'cat-vasos-accesorios',
    'Vasos y accesorios',
    'vasos-accesorios',
    'Vasos, tapas y accesorios operativos para cafeteria, vending y take away.',
    null,
    20,
    true,
    true,
    'Vasos y accesorios | SMK Vending',
    'Vasos, tapas y accesorios operativos para cafeteria, vending y take away.',
    null
  ),
  (
    'cat-maquinas',
    'Maquinas',
    'maquinas',
    'Maquinas de cafe y vending para operacion profesional.',
    null,
    30,
    true,
    true,
    'Maquinas | SMK Vending',
    'Maquinas de cafe y vending para operacion profesional.',
    null
  )
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  parent_id = excluded.parent_id,
  sort_order = excluded.sort_order,
  is_visible = excluded.is_visible,
  is_active = excluded.is_active,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  image_url = excluded.image_url;

insert into public.categories (
  id,
  name,
  slug,
  description,
  parent_id,
  sort_order,
  is_visible,
  is_active,
  seo_title,
  seo_description,
  image_url
)
values
  (
    'cat-cafe-grano',
    'Cafe en grano',
    'cafe-en-grano',
    'Cafe en grano para espresso, maquinas profesionales y operacion diaria.',
    'cat-cafe-insumos',
    11,
    true,
    true,
    'Cafe en grano | SMK Vending',
    'Cafe en grano para espresso, maquinas profesionales y operacion diaria.',
    null
  ),
  (
    'cat-capuchinos',
    'Capuchinos',
    'capuchinos',
    'Mezclas de capuchino para maquinas vending, autoservicio y cafeteria.',
    'cat-cafe-insumos',
    12,
    true,
    true,
    'Capuchinos | SMK Vending',
    'Mezclas de capuchino para maquinas vending, autoservicio y cafeteria.',
    null
  ),
  (
    'cat-mokachinos',
    'Mokachinos',
    'mokachinos',
    'Mezclas mokachino para preparacion profesional de bebidas calientes.',
    'cat-cafe-insumos',
    13,
    true,
    true,
    'Mokachinos | SMK Vending',
    'Mezclas mokachino para preparacion profesional de bebidas calientes.',
    null
  ),
  (
    'cat-chocolates',
    'Chocolates',
    'chocolates',
    'Chocolates e insumos de cacao para vending y cafeteria.',
    'cat-cafe-insumos',
    14,
    true,
    true,
    'Chocolates | SMK Vending',
    'Chocolates e insumos de cacao para vending y cafeteria.',
    null
  ),
  (
    'cat-chai-te',
    'Chai / Te instantaneo',
    'chai-te-instantaneo',
    'Bebidas instantaneas de chai, te y preparaciones solubles.',
    'cat-cafe-insumos',
    15,
    true,
    true,
    'Chai / Te instantaneo | SMK Vending',
    'Bebidas instantaneas de chai, te y preparaciones solubles.',
    null
  ),
  (
    'cat-leches-toppings',
    'Leches / Toppings',
    'leches-toppings',
    'Leches, toppings y complementos para maquinas de cafe y vending.',
    'cat-cafe-insumos',
    16,
    true,
    true,
    'Leches / Toppings | SMK Vending',
    'Leches, toppings y complementos para maquinas de cafe y vending.',
    null
  ),
  (
    'cat-vasos-polipapel',
    'Vasos polipapel',
    'vasos-polipapel',
    'Vasos polipapel para bebidas calientes, cafeteria y take away.',
    'cat-vasos-accesorios',
    21,
    true,
    true,
    'Vasos polipapel | SMK Vending',
    'Vasos polipapel para bebidas calientes, cafeteria y take away.',
    null
  ),
  (
    'cat-vasos-eco-ripple',
    'Vasos eco / ripple',
    'vasos-eco-ripple',
    'Vasos eco y ripple para operaciones con foco sustentable.',
    'cat-vasos-accesorios',
    22,
    true,
    true,
    'Vasos eco / ripple | SMK Vending',
    'Vasos eco y ripple para operaciones con foco sustentable.',
    null
  ),
  (
    'cat-tapas',
    'Tapas',
    'tapas',
    'Tapas para vasos y formatos horeca, vending y take away.',
    'cat-vasos-accesorios',
    23,
    true,
    true,
    'Tapas | SMK Vending',
    'Tapas para vasos y formatos horeca, vending y take away.',
    null
  ),
  (
    'cat-revolvedores',
    'Revolvedores',
    'revolvedores',
    'Revolvedores y accesorios menores para estaciones de cafe.',
    'cat-vasos-accesorios',
    24,
    true,
    true,
    'Revolvedores | SMK Vending',
    'Revolvedores y accesorios menores para estaciones de cafe.',
    null
  ),
  (
    'cat-maquinas-cafe',
    'Maquinas de cafe',
    'maquinas-cafe',
    'Maquinas de cafe para oficinas, retail, cafeteria y alto flujo.',
    'cat-maquinas',
    31,
    true,
    true,
    'Maquinas de cafe | SMK Vending',
    'Maquinas de cafe para oficinas, retail, cafeteria y alto flujo.',
    null
  ),
  (
    'cat-maquinas-vending',
    'Maquinas vending',
    'maquinas-vending',
    'Maquinas vending y soluciones automaticas para autoservicio.',
    'cat-maquinas',
    32,
    true,
    true,
    'Maquinas vending | SMK Vending',
    'Maquinas vending y soluciones automaticas para autoservicio.',
    null
  )
on conflict (id) do update
set
  name = excluded.name,
  slug = excluded.slug,
  description = excluded.description,
  parent_id = excluded.parent_id,
  sort_order = excluded.sort_order,
  is_visible = excluded.is_visible,
  is_active = excluded.is_active,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  image_url = excluded.image_url;

insert into public.products (
  id,
  category_id,
  name,
  slug,
  sku,
  ean,
  brand,
  short_description,
  long_description,
  price_clp_tax_inc,
  net_price_clp,
  gross_price_clp,
  stock_quantity,
  availability_status,
  publication_status,
  is_featured,
  sort_order,
  seo_title,
  seo_description,
  primary_image_path,
  highlights,
  gallery_images
)
values
  (
    'regilait-topping-2',
    'cat-leches-toppings',
    'Leche Liofilizada Regilait Topping-2',
    'leche-liofilizada-regilait-topping-2',
    'REG-10100100',
    '3043937103250',
    'Regilait',
    'Leche liofilizada para maquinas de cafe y vending.',
    'Leche liofilizada para maquinas de cafe y vending. Producto del portafolio Barry Callebaut. [PENDIENTE DEFINIR PRECIO]',
    0,
    0,
    0,
    null,
    'sold_out',
    'draft',
    false,
    200,
    'Leche Liofilizada Regilait Topping-2 | SMK Vending',
    'Leche liofilizada para maquinas de cafe y vending. Precio pendiente.',
    null,
    '["Producto para vending", "Formato profesional", "Precio pendiente"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'regilait-skimmed',
    'cat-leches-toppings',
    'Leche Liofilizada Regilait Skimmed',
    'leche-liofilizada-regilait-skimmed',
    'REG-10101300',
    '3043932753702',
    'Regilait',
    'Leche liofilizada descremada para preparacion de bebidas calientes.',
    'Leche liofilizada descremada para preparacion de bebidas calientes. Producto del portafolio Barry Callebaut. [PENDIENTE DEFINIR PRECIO]',
    0,
    0,
    0,
    null,
    'sold_out',
    'draft',
    false,
    201,
    'Leche Liofilizada Regilait Skimmed | SMK Vending',
    'Leche liofilizada descremada para preparacion de bebidas calientes. Precio pendiente.',
    null,
    '["Producto para vending", "Formato profesional", "Precio pendiente"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'van-houten-vh12',
    'cat-chocolates',
    'Chocolate Van Houten VH12',
    'chocolate-van-houten-vh12',
    'VM-VH12JH-V17',
    '7340161402002',
    'Van Houten',
    'Chocolate en polvo para maquinas de cafe, vending y preparacion profesional.',
    'Chocolate en polvo para maquinas de cafe, vending y preparacion profesional. Producto del portafolio Barry Callebaut. [PENDIENTE DEFINIR PRECIO]',
    0,
    0,
    0,
    null,
    'sold_out',
    'draft',
    false,
    202,
    'Chocolate Van Houten VH12 | SMK Vending',
    'Chocolate en polvo para maquinas de cafe, vending y preparacion profesional. Precio pendiente.',
    null,
    '["Chocolate profesional", "Uso vending", "Precio pendiente"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'caprimo-cappuccino-speculos',
    'cat-capuchinos',
    'Caprimo Cappuccino Speculos',
    'caprimo-cappuccino-speculos',
    'VM-53270-V17',
    '7350022399167',
    'Caprimo',
    'Cappuccino sabor Speculos para maquinas vending y cafeteria.',
    'Cappuccino sabor Speculos para maquinas vending y cafeteria. Producto del portafolio Barry Callebaut. [PENDIENTE DEFINIR PRECIO]',
    0,
    0,
    0,
    null,
    'sold_out',
    'draft',
    false,
    203,
    'Caprimo Cappuccino Speculos | SMK Vending',
    'Cappuccino sabor Speculos para maquinas vending y cafeteria. Precio pendiente.',
    null,
    '["Sabor Speculos", "Uso vending", "Precio pendiente"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'caprimo-cappuccino-noisette',
    'cat-capuchinos',
    'Caprimo Cappuccino Noisette',
    'caprimo-cappuccino-noisette',
    'VM-53285-V17',
    '7340161401227',
    'Caprimo',
    'Cappuccino sabor Noisette para preparacion profesional.',
    'Cappuccino sabor Noisette para preparacion profesional. Producto del portafolio Barry Callebaut. [PENDIENTE DEFINIR PRECIO]',
    0,
    0,
    0,
    null,
    'sold_out',
    'draft',
    false,
    204,
    'Caprimo Cappuccino Noisette | SMK Vending',
    'Cappuccino sabor Noisette para preparacion profesional. Precio pendiente.',
    null,
    '["Sabor Noisette", "Uso vending", "Precio pendiente"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'caprimo-cappuccino-caramelo',
    'cat-capuchinos',
    'Caprimo Cappuccino Caramelo',
    'caprimo-cappuccino-caramelo',
    'VM-51206-V17',
    '7350022390669',
    'Caprimo',
    'Cappuccino sabor caramelo para maquinas de cafe y vending.',
    'Cappuccino sabor caramelo para maquinas de cafe y vending. Producto del portafolio Barry Callebaut. [PENDIENTE DEFINIR PRECIO]',
    0,
    0,
    0,
    null,
    'sold_out',
    'draft',
    false,
    205,
    'Caprimo Cappuccino Caramelo | SMK Vending',
    'Cappuccino sabor caramelo para maquinas de cafe y vending. Precio pendiente.',
    null,
    '["Sabor caramelo", "Uso vending", "Precio pendiente"]'::jsonb,
    '[]'::jsonb
  ),
  (
    'caprimo-capuccino-vainilla-ls',
    'cat-capuchinos',
    'Caprimo Capuccino Vainilla LS',
    'caprimo-capuccino-vainilla-ls',
    'VM-53284-V17',
    '7340161401210',
    'Caprimo',
    'Cappuccino vainilla LS para maquinas vending y cafeteria.',
    'Cappuccino vainilla LS para maquinas vending y cafeteria. Producto del portafolio Barry Callebaut. [PENDIENTE DEFINIR PRECIO]',
    0,
    0,
    0,
    null,
    'sold_out',
    'draft',
    false,
    206,
    'Caprimo Capuccino Vainilla LS | SMK Vending',
    'Cappuccino vainilla LS para maquinas vending y cafeteria. Precio pendiente.',
    null,
    '["Sabor vainilla", "Uso vending", "Precio pendiente"]'::jsonb,
    '[]'::jsonb
  )
on conflict (id) do update
set
  category_id = excluded.category_id,
  name = excluded.name,
  slug = excluded.slug,
  sku = excluded.sku,
  ean = excluded.ean,
  brand = excluded.brand,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  price_clp_tax_inc = excluded.price_clp_tax_inc,
  net_price_clp = excluded.net_price_clp,
  gross_price_clp = excluded.gross_price_clp,
  stock_quantity = excluded.stock_quantity,
  availability_status = excluded.availability_status,
  publication_status = excluded.publication_status,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  primary_image_path = excluded.primary_image_path,
  highlights = excluded.highlights,
  gallery_images = excluded.gallery_images;

