-- Phase 2B: idempotent seed for missing Mokador, Schoppe and Laqtia products.
-- Existing products are updated by canonical slug, SKU or known legacy slug.
-- Prices remain explicit placeholders: 0 net / 0 gross until commercial values are defined.

with product_seed (
  id,
  legacy_slug,
  category_id,
  name,
  slug,
  sku,
  ean,
  brand,
  short_description,
  long_description,
  price_clp_tax_inc,
  net_price_clp,
  gross_price_clp,
  stock_quantity,
  availability_status,
  publication_status,
  is_featured,
  sort_order,
  seo_title,
  seo_description,
  primary_image_path,
  highlights,
  gallery_images
) as (
  values
    (
      'mokador-100-arabica-bio',
      null,
      'cat-cafe-grano',
      'Mokador 100% Arabica Bio',
      'mokador-100-arabica-bio',
      'pendiente-mokador-100-arabica-bio',
      null,
      'Mokador',
      'Cafe Mokador 100% Arabica Bio para cafeteria, vending y consumo profesional.',
      'Cafe Mokador 100% Arabica Bio para cafeteria, vending y consumo profesional. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      230,
      'Mokador 100% Arabica Bio | SMK Vending',
      'Cafe Mokador 100% Arabica Bio para cafeteria, vending y consumo profesional. Precio pendiente.',
      '/catalog/cutouts/arabicabio.png',
      '["Cafe en grano", "Marca Mokador", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'mokador-oro-blend',
      null,
      'cat-cafe-grano',
      'Mokador Oro Blend',
      'mokador-oro-blend',
      'pendiente-mokador-oro-blend',
      null,
      'Mokador',
      'Blend de cafe Mokador Oro para maquinas de cafe y preparacion profesional.',
      'Blend de cafe Mokador Oro para maquinas de cafe y preparacion profesional. [PENDIENTE DEFINIR PRECIO] [PENDIENTE CARGAR IMAGEN]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      231,
      'Mokador Oro Blend | SMK Vending',
      'Blend de cafe Mokador Oro para maquinas de cafe y preparacion profesional. Precio pendiente.',
      '/catalog/cutouts/placeholders/mokador-oro-blend.svg',
      '["Cafe en grano", "Blend profesional", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'mokador-brio-100',
      null,
      'cat-cafe-grano',
      'Mokador Brio 100',
      'mokador-brio-100',
      'pendiente-mokador-brio-100',
      null,
      'Mokador',
      'Cafe Mokador Brio 100 para cafeteria, vending y empresas.',
      'Cafe Mokador Brio 100 para cafeteria, vending y empresas. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      232,
      'Mokador Brio 100 | SMK Vending',
      'Cafe Mokador Brio 100 para cafeteria, vending y empresas. Precio pendiente.',
      '/catalog/cutouts/brio.png',
      '["Cafe en grano", "Uso profesional", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'mokador-extra-cream',
      null,
      'cat-cafe-grano',
      'Mokador Extra Cream',
      'mokador-extra-cream',
      'pendiente-mokador-extra-cream',
      null,
      'Mokador',
      'Cafe Mokador Extra Cream con perfil cremoso para maquinas de cafe y vending.',
      'Cafe Mokador Extra Cream con perfil cremoso para maquinas de cafe y vending. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      233,
      'Mokador Extra Cream | SMK Vending',
      'Cafe Mokador Extra Cream con perfil cremoso para maquinas de cafe y vending. Precio pendiente.',
      '/catalog/cutouts/extracream.png',
      '["Cafe en grano", "Perfil cremoso", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'schoppe-caramel-302',
      null,
      'cat-capuchinos',
      'Schoppe Caramel 302',
      'schoppe-caramel-302',
      'pendiente-schoppe-caramel-302',
      null,
      'Schoppe',
      'Bebida instantanea Schoppe sabor caramelo para maquinas vending y cafeteria.',
      'Bebida instantanea Schoppe sabor caramelo para maquinas vending y cafeteria. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      234,
      'Schoppe Caramel 302 | SMK Vending',
      'Bebida instantanea Schoppe sabor caramelo para maquinas vending y cafeteria. Precio pendiente.',
      '/catalog/cutouts/302.png',
      '["Sabor caramelo", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'schoppe-vainilla-301',
      null,
      'cat-capuchinos',
      'Schoppe Vainilla 301',
      'schoppe-vainilla-301',
      'pendiente-schoppe-vainilla-301',
      null,
      'Schoppe',
      'Bebida instantanea Schoppe sabor vainilla para vending y preparacion profesional.',
      'Bebida instantanea Schoppe sabor vainilla para vending y preparacion profesional. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      235,
      'Schoppe Vainilla 301 | SMK Vending',
      'Bebida instantanea Schoppe sabor vainilla para vending y preparacion profesional. Precio pendiente.',
      '/catalog/cutouts/301.svg',
      '["Sabor vainilla", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'schoppe-noisette-303',
      'schoppe-noisete-303',
      'cat-capuchinos',
      'Schoppe Noisette 303',
      'schoppe-noisette-303',
      'pendiente-schoppe-noisette-303',
      null,
      'Schoppe',
      'Bebida instantanea Schoppe sabor noisette para maquinas vending y cafeteria.',
      'Bebida instantanea Schoppe sabor noisette para maquinas vending y cafeteria. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      236,
      'Schoppe Noisette 303 | SMK Vending',
      'Bebida instantanea Schoppe sabor noisette para maquinas vending y cafeteria. Precio pendiente.',
      '/catalog/cutouts/303.svg',
      '["Sabor noisette", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'schoppe-choco-107',
      null,
      'cat-chocolates',
      'Schoppe Choco 107',
      'schoppe-choco-107',
      'pendiente-schoppe-choco-107',
      null,
      'Schoppe',
      'Chocolate instantaneo Schoppe Choco 107 para vending y cafeteria.',
      'Chocolate instantaneo Schoppe Choco 107 para vending y cafeteria. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      237,
      'Schoppe Choco 107 | SMK Vending',
      'Chocolate instantaneo Schoppe Choco 107 para vending y cafeteria. Precio pendiente.',
      '/catalog/cutouts/107.png',
      '["Chocolate instantaneo", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'schoppe-instant-tea-505',
      null,
      'cat-chai-te',
      'Schoppe Instant Tea 505',
      'schoppe-instant-tea-505',
      'pendiente-schoppe-instant-tea-505',
      null,
      'Schoppe',
      'Te instantaneo Schoppe Instant Tea 505 para maquinas vending y bebidas calientes.',
      'Te instantaneo Schoppe Instant Tea 505 para maquinas vending y bebidas calientes. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      238,
      'Schoppe Instant Tea 505 | SMK Vending',
      'Te instantaneo Schoppe Instant Tea 505 para maquinas vending y bebidas calientes. Precio pendiente.',
      '/catalog/cutouts/505.svg',
      '["Te instantaneo", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'laqtia-mocacino',
      null,
      'cat-mokachinos',
      'Laqtia Mocacino',
      'laqtia-mocacino',
      'pendiente-laqtia-mocacino',
      null,
      'Laqtia',
      'Mocacino Laqtia para maquinas vending, cafeteria y preparacion profesional.',
      'Mocacino Laqtia para maquinas vending, cafeteria y preparacion profesional. [PENDIENTE DEFINIR PRECIO] [PENDIENTE CARGAR IMAGEN]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      239,
      'Laqtia Mocacino | SMK Vending',
      'Mocacino Laqtia para maquinas vending, cafeteria y preparacion profesional. Precio pendiente.',
      '/catalog/cutouts/placeholders/laqtia-mocacino.svg',
      '["Mocacino", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'laqtia-capuccino',
      null,
      'cat-capuchinos',
      'Laqtia Capuccino',
      'laqtia-capuccino',
      'pendiente-laqtia-capuccino',
      null,
      'Laqtia',
      'Capuccino Laqtia para maquinas vending y cafeteria.',
      'Capuccino Laqtia para maquinas vending y cafeteria. [PENDIENTE DEFINIR PRECIO] [PENDIENTE CARGAR IMAGEN]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      240,
      'Laqtia Capuccino | SMK Vending',
      'Capuccino Laqtia para maquinas vending y cafeteria. Precio pendiente.',
      '/catalog/cutouts/placeholders/laqtia-capuccino.svg',
      '["Capuccino", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'laqtia-french-vainilla',
      null,
      'cat-capuchinos',
      'Laqtia French Vainilla',
      'laqtia-french-vainilla',
      'pendiente-laqtia-french-vainilla',
      null,
      'Laqtia',
      'Bebida Laqtia French Vainilla para vending y preparacion profesional.',
      'Bebida Laqtia French Vainilla para vending y preparacion profesional. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      241,
      'Laqtia French Vainilla | SMK Vending',
      'Bebida Laqtia French Vainilla para vending y preparacion profesional. Precio pendiente.',
      '/catalog/cutouts/French%20Vainilla.png',
      '["French Vainilla", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'laqtia-leche-topping',
      null,
      'cat-leches-toppings',
      'Laqtia Leche Topping',
      'laqtia-leche-topping',
      'pendiente-laqtia-leche-topping',
      null,
      'Laqtia',
      'Leche topping Laqtia para maquinas de cafe, vending y bebidas calientes.',
      'Leche topping Laqtia para maquinas de cafe, vending y bebidas calientes. [PENDIENTE DEFINIR PRECIO] [PENDIENTE CARGAR IMAGEN]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      242,
      'Laqtia Leche Topping | SMK Vending',
      'Leche topping Laqtia para maquinas de cafe, vending y bebidas calientes. Precio pendiente.',
      '/catalog/cutouts/placeholders/laqtia-leche-topping.svg',
      '["Leche topping", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'laqtia-chocolate-22-cacao-q15',
      null,
      'cat-chocolates',
      'Laqtia Chocolate 22% Cacao Q15',
      'laqtia-chocolate-22-cacao-q15',
      'pendiente-laqtia-chocolate-22-cacao-q15',
      null,
      'Laqtia',
      'Chocolate Laqtia 22% cacao Q15 para vending y cafeteria.',
      'Chocolate Laqtia 22% cacao Q15 para vending y cafeteria. [PENDIENTE DEFINIR PRECIO] [PENDIENTE CARGAR IMAGEN]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      243,
      'Laqtia Chocolate 22% Cacao Q15 | SMK Vending',
      'Chocolate Laqtia 22% cacao Q15 para vending y cafeteria. Precio pendiente.',
      '/catalog/cutouts/placeholders/laqtia-chocolate-22-cacao-q15.svg',
      '["22% cacao", "Chocolate para vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    ),
    (
      'laqtia-natur-basic',
      null,
      'cat-leches-toppings',
      'Laqtia Natur Basic',
      'laqtia-natur-basic',
      'pendiente-laqtia-natur-basic',
      null,
      'Laqtia',
      'Producto Laqtia Natur Basic para preparacion de bebidas calientes en maquinas vending.',
      'Producto Laqtia Natur Basic para preparacion de bebidas calientes en maquinas vending. [PENDIENTE DEFINIR PRECIO]',
      0,
      0,
      0,
      null,
      'sold_out'::public.availability_status,
      'draft'::public.publication_status,
      false,
      244,
      'Laqtia Natur Basic | SMK Vending',
      'Producto Laqtia Natur Basic para preparacion de bebidas calientes en maquinas vending. Precio pendiente.',
      '/catalog/cutouts/laqtia-natur-basic.png',
      '["Linea Natur Basic", "Uso vending", "Precio pendiente"]'::jsonb,
      '[]'::jsonb
    )
),
matched_products as (
  select distinct on (seed.id)
    seed.id as seed_id,
    product.id as product_id
  from product_seed seed
  join public.products product
    on product.slug = seed.slug
    or product.sku = seed.sku
    or (
      seed.legacy_slug is not null
      and product.slug = seed.legacy_slug
    )
  order by
    seed.id,
    case
      when product.slug = seed.slug then 0
      when product.sku = seed.sku then 1
      else 2
    end,
    product.created_at nulls last,
    product.id
),
updated_products as (
  update public.products product
  set
    category_id = seed.category_id,
    name = seed.name,
    slug = seed.slug,
    sku = seed.sku,
    ean = seed.ean,
    brand = seed.brand,
    short_description = seed.short_description,
    long_description = seed.long_description,
    price_clp_tax_inc = seed.price_clp_tax_inc::integer,
    net_price_clp = seed.net_price_clp::integer,
    gross_price_clp = seed.gross_price_clp::integer,
    stock_quantity = seed.stock_quantity::integer,
    availability_status = seed.availability_status,
    publication_status = seed.publication_status,
    is_featured = seed.is_featured,
    sort_order = seed.sort_order::integer,
    seo_title = seed.seo_title,
    seo_description = seed.seo_description,
    primary_image_path = seed.primary_image_path,
    highlights = seed.highlights,
    gallery_images = seed.gallery_images
  from product_seed seed
  join matched_products matched
    on matched.seed_id = seed.id
  where product.id = matched.product_id
  returning product.id
)
insert into public.products (
  id,
  category_id,
  name,
  slug,
  sku,
  ean,
  brand,
  short_description,
  long_description,
  price_clp_tax_inc,
  net_price_clp,
  gross_price_clp,
  stock_quantity,
  availability_status,
  publication_status,
  is_featured,
  sort_order,
  seo_title,
  seo_description,
  primary_image_path,
  highlights,
  gallery_images
)
select
  seed.id,
  seed.category_id,
  seed.name,
  seed.slug,
  seed.sku,
  seed.ean,
  seed.brand,
  seed.short_description,
  seed.long_description,
  seed.price_clp_tax_inc::integer,
  seed.net_price_clp::integer,
  seed.gross_price_clp::integer,
  seed.stock_quantity::integer,
  seed.availability_status,
  seed.publication_status,
  seed.is_featured,
  seed.sort_order::integer,
  seed.seo_title,
  seed.seo_description,
  seed.primary_image_path,
  seed.highlights,
  seed.gallery_images
from product_seed seed
where not exists (
  select 1
  from matched_products matched
  where matched.seed_id = seed.id
)
on conflict (id) do update
set
  category_id = excluded.category_id,
  name = excluded.name,
  slug = excluded.slug,
  sku = excluded.sku,
  ean = excluded.ean,
  brand = excluded.brand,
  short_description = excluded.short_description,
  long_description = excluded.long_description,
  price_clp_tax_inc = excluded.price_clp_tax_inc,
  net_price_clp = excluded.net_price_clp,
  gross_price_clp = excluded.gross_price_clp,
  stock_quantity = excluded.stock_quantity,
  availability_status = excluded.availability_status,
  publication_status = excluded.publication_status,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order,
  seo_title = excluded.seo_title,
  seo_description = excluded.seo_description,
  primary_image_path = excluded.primary_image_path,
  highlights = excluded.highlights,
  gallery_images = excluded.gallery_images;
